apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Chart.Name }}-pvc
spec:
  storageClassName: {{ .Values.influxdb.pvc.storage.name }}
  resources:
    requests:
      storage: {{ .Values.influxdb.pvc.storage.size }}
  volumeMode: Filesystem
  accessModes:
  {{- range .Values.influxdb.pvc.accessModes }}
    - {{ . }}
  {{- end }}
