apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
type: Opaque
data:
  DOCKER_INFLUXDB_INIT_MODE: "setup"
  DOCKER_INFLUXDB_INIT_USERNAME: {{ .Values.influxdb.init.user | quote }}
  DOCKER_INFLUXDB_INIT_PASSWORD: {{ randAlphaNum 16 | b64enc | quote }}
  DOCKER_INFLUXDB_INIT_ORG: {{ .Values.influxdb.init.organization | quote }}
  DOCKER_INFLUXDB_INIT_BUCKET: {{ .Values.influxdb.init.bucket | quote }}
