apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.influxdb.image.port | int }}
    targetPort: {{ .Values.influxdb.image.port | int }}
    protocol: TCP
  selector:
    app: {{ .Chart.Name }}