apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  replicas: {{ .Values.influxdb.replicas }}    
  minReadySeconds: 20
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.influxdb.image.repository }}:{{ .Values.influxdb.image.tag }}"
          ports:
            - containerPort: {{ .Values.influxdb.image.port | int }}
          envFrom:
            - secretRef:
                name: {{ .Chart.Name }}-secret
          volumeMounts:
            - name: data
              mountPath: /var/lib/influxdb2
          resources:
            limits:
              cpu: {{ .Values.influxdb.resources.limits.cpu }}
              memory: {{ .Values.influxdb.resources.limits.memory }}
            requests:
              cpu: {{ .Values.influxdb.resources.requests.cpu }}
              memory: {{ .Values.influxdb.resources.requests.memory }}          
          livenessProbe:
            httpGet:
              path: {{ .Values.influxdb.probe.path | quote }}
              port: {{ .Values.influxdb.image.port | int }}
              scheme: {{ .Values.influxdb.probe.scheme | quote }}
            periodSeconds: {{ .Values.influxdb.probe.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.influxdb.probe.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.influxdb.probe.liveness.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.influxdb.probe.path | quote }}
              port: {{ .Values.influxdb.image.port | int }}
              scheme: {{ .Values.influxdb.probe.scheme | quote }}
            periodSeconds: {{ .Values.influxdb.probe.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.influxdb.probe.readiness.timeoutSeconds }}
            successThreshold: {{ .Values.influxdb.probe.readiness.successThreshold }}
            failureThreshold: {{ .Values.influxdb.probe.readiness.failureThreshold }}
          startupProbe:
            httpGet:
              path: {{ .Values.influxdb.probe.path | quote }}
              port: {{ .Values.influxdb.image.port | int }}
              scheme: {{ .Values.influxdb.probe.scheme | quote }}
            initialDelaySeconds: {{ .Values.influxdb.probe.startup.initialDelaySeconds }}
            periodSeconds: {{ .Values.influxdb.probe.startup.periodSeconds }}
            timeoutSeconds: {{ .Values.influxdb.probe.startup.timeoutSeconds }}
            failureThreshold: {{ .Values.influxdb.probe.startup.failureThreshold }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: {{ .Values.influxdb.pvc.storage.name }}
        resources:
          requests:
            storage: {{ .Values.influxdb.pvc.storage.size }}
        volumeMode: Filesystem
        accessModes:
        {{- range .Values.influxdb.pvc.accessModes }}
          - {{ . }}
        {{- end }}

