---
server:
  replicas: 2
  image:
    name: nginx
    tag: latest
  port: 80
  terminationGracePeriodSeconds: 10
  pvc:
    storage:
      class: hostpath
      size: 500Mi
    accessModes:
      - ReadWriteMany
  volumes:
    mountPath: /usr/share/nginx/upload
  resources:
    limits:
      cpu: 500m
      memory: 1000Mi
    requests:
      cpu: 250m
      memory: 500Mi
