kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Chart.Name }}-cm
data:
  location.conf: |-
    server {
        location {{ .Values.server.volumes.mountPath }}/ {
            limit_except POST              { deny all; }
            client_body_in_file_only       on;

            return 201 $request_body_file;
        }
    }
