kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Chart.Name }}-cm
data:
  location.conf: |-
    server {
        location {{ .Values.server.volumes.mountPath }} {
            root {{ .Values.server.volumes.mountPath }};
        }
    }
