kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Chart.Name }}-cm
data:
  location.conf: |-
    server {
      listen       8080;
      root {{ .Values.server.volumes.mountPath }};

      location / {
        limit_except POST              { deny all; }
        client_body_in_file_only       on;

        return 200 $request_body_file;
      }
    }
