---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.server.port }}
    targetPort: {{ .Values.server.port }}
    protocol: TCP
  selector:
    app: {{ .Chart.Name }}
