---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  serviceName: {{ .Chart.Name }}-service
  replicas: {{ .Values.server.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.server.terminationGracePeriodSeconds }}
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: {{ .Chart.Name }}-pvc
        - name: config
          configMap:
            name: {{ .Chart.Name }}-cm
      containers:
        - name: nginx
          image: "{{ .Values.server.image.name }}:{{ .Values.server.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.server.port | int }}
              name: web
          volumeMounts:
            - name: storage
              mountPath: {{ .Values.server.volumes.mountPath }}
            - name: config
              mountPath: /etc/nginx/conf.d/upload.conf
              subPath: upload.conf
          resources:
            limits:
              cpu: {{ .Values.server.resources.limits.cpu }}
              memory: {{ .Values.server.resources.limits.memory }}
            requests:
              cpu: {{ .Values.server.resources.requests.cpu }}
              memory: {{ .Values.server.resources.requests.memory }} 
