---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-demo
  namespace: argocd
spec:
  selector:
    matchLabels:
      app: k8s-demo
  template:
    metadata:
      labels:
        app: k8s-demo
    spec:
      containers:
        - name: k8s-demo
          image: kuckchuck96/k8s-demo:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
