apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: go-kube-demo-pvc
spec:
  storageClassName: hostpath
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
